### ISSUE TITLE
Commit does not work

### ISSUE THREAD

**Issue by Bulldawzer** [Otakumouse/stormshade#1]
It autodetects a gamepath that doesn't exist, looking for a .ini that also doesn't exist (path was D:\games\...)
I got it to work by using your old commit here https://github.com/Otakumouse/stormshade/tree/47f93305f95732dabcea8a24d52a5f5438a7ae3c .

**Comment by kiasta** [comment]
The ReShade.ini file seems to have hardcoded paths. Even changing the path in the ReShade.ini file, the presets are not loading and the reload button seems to do nothing.
